[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 1

[[main]]
    identifier = "leituras"
    name = "Leituras"
    url = "/leituras"
    weight = 2

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3

    
# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "#"
    weight = 1

[[social]]
    identifier = "instagram"
    name = "Instagram"
    url = "#"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "#"
    weight = 3